project:
  type: website

website:
  reader-mode: true
  sidebar:
    contents: auto
  navbar:
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    toc: true
    code-fold: true
    lightbox: auto

bibliography:
  - ../share/bibliography/research.bib

wrap: preserve